name: CI

on: [ "push", "pull_request" ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.x

      - name: Build
        run: dotnet build SpeedrunTasks/SpeedrunTasks.csproj --configuration Release

      - uses: actions/upload-artifact@v2
        with:
          name: SpeedrunTasks.dll
          path: SpeedrunTasks/bin/Release/netstandard2.1/SpeedrunTasks.dll
